# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: I'm Ping # ex. I m Chuan
name: Ping # ex. DONGChuan
email: 1374161425@qq.com
location: 深圳市 # ex. Nice, France
company: 保密
company_url: my_company_website
github_url: https://github.com/wananshine # ex. https://github.com/DONGChuan
github_username: wananshine  # ex. DONGChuan
description: description_of_your_web_site
favicon: favicon.png # Image must be in assets/images
repository: "wananshine/PingBlog.github.io/" # ex. DONGChuan/DONGChuan.github.io

# The base hostname & protocol for your site
# For local test, please use http://localhost:4000
# For production, use your github page url. ex. http://dongchuan.github.io
url: "https://wananshine.github.io/PingBlog.github.io"
baseurl: "/PingBlog.github.io/" # the subpath of your site, e.g. /blog

## Gem
gems:
  - jekyll-paginate
  - jekyll-geo-pattern
  - rouge
  - kramdown
  - jekyll-github-metadata

# Build settings
markdown: kramdown
highlighter: rouge
lsi:         false
excerpt_separator: "\n\n"

source:      .
destination: ./_site

quiet:    false
defaults: []

kramdown:
  input: GFM
  enable_coderay: true

# Disque
disque: https://wananshine.github.io/PingBlog.github.io/ # ex. httpdongchuangithubio.disqus.com

# Pagination
paginate: 10
paginate_path: 'page:num'

# Navigation. If you do not like these modules, just remove them :D
navs:
  -
    href: https://wananshine.github.io/PingBlog.github.io/
    label: Home

  # -
  #   href: https://wananshine.github.io/PingBlog.github.io/open-source
  #   label: Open-Source   #项目先隐藏

  -
    href: https://wananshine.github.io/PingBlog.github.io/blog
    label: Blog

  -
    href: https://wananshine.github.io/PingBlog.github.io/bookmark
    label: Bookmark

  -
    href: https://wananshine.github.io/PingBlog.github.io/about
    label: About

# Sidebar to show popular repo
side_bar_repo_limit: 5 # Number of repos to show

# Google Analytics
analytics :
  provider : google
  google :
      tracking_id : 'tracking_id'  # ex. UA-72165600-X


# For about.html. Fell free to create your own!
skill_software_keywords: [Java, C, C++, Qt, Python, MySQL, Oracle, SQLite, PL/SQL, Design Patterns]
skill_j2ee_keywords: [Spring, Struct, Hibernet, MyBatis, JSP]
skill_web_keywords: [HTML, CSS, JS, JQuery, Ajax, AngularJS, NodeJS, ExpressJS, MongoDB, Redis, PHP, Symfony, Boostrap]
skill_mobile_app_keywords: [Android, Sketch UI Desgin]
